services:
  postgres:
    image: postgres:15-alpine
    container_name: aurora_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aurora_password
      POSTGRES_DB: aurora_erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aurora_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: aurora_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aurora.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - aurora_net

  minio:
    image: minio/minio
    container_name: aurora_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - aurora_net

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - aurora_net
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; /usr/bin/mc mb --ignore-existing myminio/invoices; /usr/bin/mc anonymous set public myminio/invoices; exit 0; "

  backend:
    build:
      context: ./backend
      dockerfile: Aurora.API/Dockerfile
    container_name: aurora_backend
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=aurora_erp;Username=postgres;Password=aurora_password
      - ASPNETCORE_ENVIRONMENT=Production
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin
      - Minio__BucketName=invoices
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aurora_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://auroraerp.softnexus.com.br/api
    container_name: aurora_frontend
    environment:
      - VITE_API_URL=https://auroraerp.softnexus.com.br/api
    depends_on:
      - backend
    networks:
      - aurora_net

  gateway:
    build: ./gateway
    container_name: aurora_gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - aurora_net

networks:
  aurora_net:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  caddy_data:
  caddy_config:
